### ISSUE TITLE
Permissions need to be rebuilt after install

### ISSUE THREAD

**Issue by Stockfoot** [kanopi/saplings#5]
After installing the Drupal Minimal and applying the kanopi/saplings recipe, the admin shows that permissions need to be rebuilt.

**Comment by thejimbirch** [comment]
We can do this on the command line with:

`fin drush php-eval 'node_access_rebuild();'`

Things to look into:

does it happen with all recipes?
Or is it a certain module or config causing it?

This could be an issue for the recipes initiative.

Or

We could add the drush command above into our `fin recipe-apply` command if we need it all the time.

**Comment by thejimbirch** [comment]
The origin of this is the View Unpublished module.

**Comment by thejimbirch** [comment]
The View Unpublished requires a permissions rebuild after installation.  They do not do this automatically because if you install their module on a site that has a lot of content, they recommend taking a backup first.

I am going to close this as a minor annoyance.  There are core issues open that would make this module obsolete.  Hopefully they get addressed in future versions of Drupal.
